frr defaults traditional
hostname r1
service integrated-vtysh-config
log stdout
no zebra nexthop kernel enable
!
interface eth1
 ip address 198.18.0.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf cost 7
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
interface stub1
 ip address 10.10.2.1/24
 ip ospf area 0.0.0.0
 ip ospf passive
 ip ospf cost 3
!
router ospf
 ospf router-id 0.0.0.2
 maximum-paths 64
 timers throttle spf 100 200 1000
!
line vty
!
